[project]
name = "crewai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "abdul rehman", email = "157266271+moiz14553@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
crewai = "crewai:main"
piaic="crewai.main:kickoff"
routrun="crewai.main:kickoff"
routplot="crewai.main:plot"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
